"use client";

import { useState } from "react";
import type { CustomerSafeQuote } from "@/types/merchant";
import QuoteSummary from "./QuoteSummary";
import styles from "./LeadQuoteView.module.css";

// The customer's view of a quote. Reached two ways — a quote the rep prepared
// (configs and/or their statement) rendered straight from /lead/[token], and
// one the customer generated by uploading a statement themselves — and it
// looks the same either way. It only ever receives a CustomerSafeQuote: no
// margin, no cost, no floor, nothing derived from them.
//
// The quote itself renders through QuoteSummary, shared with the authenticated
// "Your Quote" tab; this component owns the public page chrome and whatever
// the merchant's next step is.
//
// THERE IS ONE ACCEPTANCE, and for almost everyone it does not happen here.
// A quote with products on it is signed and paid on HubSpot's hosted page —
// e-signature and ACH mandate in one — so the panel is one button out to it.
// EasyOB used to ask the merchant to accept first and THEN send them there to
// accept again, which is one acceptance too many. Entering billing details IS
// accepting the quote.
//
// THE MERCHANT OPENS THE DOOR. Until 2026-09-25 the HubSpot quote had to be
// published by a rep first, and a merchant who opened the link they had just
// been emailed saw "your quote is being finalised" and could do nothing at
// all. That gate is gone: "Continue to Billing" POSTs ../checkout, which
// builds and publishes the quote on the spot and hands back the hosted URL.
//
// Publishing is irreversible, so the button asks first. The confirmation talks
// about what the MERCHANT loses — the chance to have the pricing changed — not
// about HubSpot's inability to unpublish, which is not their problem.
//
// The in-app accept form below survives for exactly one case, `canAcceptHere`:
// a rate-only quote, which creates no HubSpot document at all (see the header
// on /api/lead/[token]/accept). For those merchants there is nothing to sign
// and nothing to pay, so this is their only acceptance, not a duplicate one.

type Props = {
  token: string;
  quote: CustomerSafeQuote;
  businessName: string | null;
  contactEmail: string | null;
  /**
   * HubSpot's hosted quote — sign + pay in one. Present once the quote has
   * been published; null before that, which is now the ordinary state rather
   * than a wait, because pressing the button below is what publishes it.
   */
  checkoutUrl?: string | null;
  /** True when the merchant signed the hosted quote but never finished paying. */
  signedWithoutPaying?: boolean;
  /** Rate-only: no HubSpot document exists, so the merchant accepts right here. */
  canAcceptHere?: boolean;
  /** True when this quote has already been accepted (re-opened link). */
  alreadyAccepted?: boolean;
  /** Offered only on a rep-prepared quote — lets the customer supersede it with their own statement. */
  onUploadStatement?: () => void;
};

export default function LeadQuoteView({
  token, quote, businessName, contactEmail,
  checkoutUrl = null, canAcceptHere = false, alreadyAccepted = false,
  signedWithoutPaying = false, onUploadStatement,
}: Props) {
  const [email, setEmail]         = useState(contactEmail || "");
  const [accepting, setAccepting] = useState(false);
  const [accepted, setAccepted]   = useState(alreadyAccepted);
  const [resent, setResent]       = useState(false);
  const [devUrl, setDevUrl]       = useState<string | null>(null);
  const [error, setError]         = useState<string | null>(null);

  // The billing hand-off. `confirming` is the irreversibility prompt; `going`
  // covers the publish, which is 8-12 HubSpot calls plus a ~3s link read, so
  // the merchant is told it is working rather than left on a dead button.
  const [confirming, setConfirming] = useState(false);
  const [going, setGoing]           = useState(false);
  const [goError, setGoError]       = useState<string | null>(null);

  // What the merchant is told when the quote can't be published. Never the
  // real reason: those messages name AIO's internals and the person who can
  // fix them is a rep, not this merchant (see the route's own header).
  const CHECKOUT_ERRORS: Record<string, string> = {
    link_pending: "Your quote is being finalised right now — give it a few seconds and try again.",
    not_ready: "We couldn't open billing just yet. Your AIO representative has been notified and will sort it out — no need to do anything.",
    rate_only: "This quote has nothing to bill, so there's nothing to pay. Accept it below instead.",
    no_quote: "There's no quote on this link yet.",
    expired: "This link has expired. Ask your AIO representative for a new one.",
    invalid: "This link is no longer valid. Ask your AIO representative for a new one.",
  };

  // Publishes the HubSpot quote if it isn't published yet, then sends the
  // merchant to it. Idempotent server-side, so a double click can't produce a
  // second document.
  const continueToBilling = async () => {
    if (checkoutUrl) { window.location.href = checkoutUrl; return; }
    setGoing(true);
    setGoError(null);
    try {
      const res = await fetch(`/api/lead/${token}/checkout`, { method: "POST" });
      const data = await res.json();
      if (!res.ok || !data.url) {
        setGoError(CHECKOUT_ERRORS[data.error] ?? CHECKOUT_ERRORS.not_ready);
        setGoing(false);
        setConfirming(false);
        return;
      }
      // Deliberately not resetting `going` — the navigation is the end of this
      // component's life, and flipping the button back to idle mid-redirect
      // invites a second click on a door that only opens once.
      window.location.href = data.url;
    } catch {
      setGoError(CHECKOUT_ERRORS.not_ready);
      setGoing(false);
      setConfirming(false);
    }
  };

  // Rate-only only. Accepting and re-requesting the sign-in email are the same
  // call: that route records acceptance once and issues a fresh
  // 30-minute login token every time, so a customer who let theirs expire has
  // a way back in from this page.
  const accept = async () => {
    if (!email) return;
    const wasAccepted = accepted;
    setAccepting(true);
    setResent(false);
    setError(null);
    try {
      const res = await fetch(`/api/lead/${token}/accept`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Could not accept the quote");
      setAccepted(true);
      setDevUrl(data.devUrl || null);
      if (wasAccepted) setResent(true);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not accept the quote");
    }
    setAccepting(false);
  };

  return (
    <div className={styles.page}>
      <div className={styles.container}>
        <div className={styles.quoteHead}>
          <div className={styles.quoteEyebrow}>Your Quote</div>
          <h1 className={styles.quoteBusiness}>{businessName || "Your Business"}</h1>
        </div>

        <QuoteSummary
          quote={quote}
          // Never once accepted — the accepted quote's basis is frozen, and
          // the server refuses to replace it, so offering the upload would
          // be an affordance that leads nowhere.
          basisAction={onUploadStatement && !accepted ? (
            <button type="button" onClick={onUploadStatement} className={styles.linkBtn}>
              Upload a statement instead
            </button>
          ) : undefined}
        />

        <div className={styles.panel}>
          {accepted ? (
            // Two quite different "done" states share this branch. A rate-only
            // merchant accepted with the form below and needs their login link
            // (and a way to re-request it). Everyone else signed on HubSpot,
            // and their link was emailed the moment we saw the payment.
            canAcceptHere ? (
              <div>
                <p className={styles.acceptSuccess}>
                  {resent
                    ? "New link sent. Check your email to finish setting up your account."
                    : "Quote accepted. Check your email for a link to finish setting up your account."}
                </p>
                {devUrl && (
                  <div className={styles.devUrl}>
                    Dev mode (no email configured): <a href={devUrl}>{devUrl}</a>
                  </div>
                )}
                <p className={styles.panelText}>
                  That link is good for 30 minutes. If it expired or never arrived, we&apos;ll send another.
                </p>
                <div className={styles.acceptRow}>
                  <input
                    type="email" value={email} onChange={e => setEmail(e.target.value)}
                    placeholder="you@business.com"
                    className={styles.acceptInput}
                  />
                  <button
                    onClick={accept}
                    disabled={!email || accepting}
                    className={styles.acceptBtn}
                  >
                    {accepting ? "Sending…" : "Email Me a New Link"}
                  </button>
                </div>
                {error && <div className={styles.acceptError}>{error}</div>}
              </div>
            ) : (
              <div>
                <p className={styles.acceptSuccess}>
                  You&apos;re all set — this quote is signed and your billing is in.
                </p>
                <p className={styles.panelText}>
                  We&apos;ve emailed you a link to set up your account and finish onboarding. If it
                  expired, you can request a new one from the sign-in page.
                </p>
                <div className={styles.acceptRow}>
                  <a href="/customer/login" className={styles.acceptBtn}>Sign In →</a>
                </div>
              </div>
            )
          ) : signedWithoutPaying ? (
            // Signed, not paid. The two happen on the same HubSpot page but
            // are separate acts, and only the second one accepts the quote —
            // so this merchant believes they are finished and is looking at a
            // checklist that has unlocked nothing. Say exactly that, and send
            // them back to the same page to finish.
            <>
              <h2 className={styles.panelTitle}>You&apos;ve signed — one step left</h2>
              <p className={styles.panelText}>
                Thanks for signing. Your billing details still need to go in before we can set up
                your account and open the rest of your onboarding. It&apos;s the same page you
                signed on, and it takes a minute.
              </p>
              <div className={styles.acceptRow}>
                <button onClick={continueToBilling} disabled={going} className={styles.acceptBtn}>
                  {going ? "Opening…" : "Enter Billing Details →"}
                </button>
              </div>
              {goError && <div className={styles.acceptError}>{goError}</div>}
            </>
          ) : confirming ? (
            // The one-way door, in the merchant's own terms. What they lose is
            // the chance to have the pricing changed — say that, rather than
            // anything about HubSpot.
            <>
              <h2 className={styles.panelTitle}>Ready to lock this quote in?</h2>
              <p className={styles.panelText}>
                Continuing prepares your final quote and takes you to a secure page to sign it and
                set up payment. From that point the pricing and products above are fixed — if
                anything looks wrong, talk to your AIO representative first and they&apos;ll put
                together a new one for you.
              </p>
              <div className={styles.acceptRow}>
                <button onClick={continueToBilling} disabled={going} className={styles.acceptBtn}>
                  {going ? "Preparing your quote…" : "Yes, continue to billing →"}
                </button>
                <button
                  onClick={() => { setConfirming(false); setGoError(null); }}
                  disabled={going}
                  className={styles.secondaryBtn}
                >
                  Not yet
                </button>
              </div>
              {goError && <div className={styles.acceptError}>{goError}</div>}
            </>
          ) : canAcceptHere ? (
            // Rate-only: no HubSpot document exists or ever will, so there is
            // nothing to sign and nothing to pay. This form is these
            // merchants' only acceptance, not a duplicate of one.
            <>
              <h2 className={styles.panelTitle}>Ready to move forward?</h2>
              <p className={styles.panelText}>
                Accept this quote and we&apos;ll create your account so you can finish onboarding
                yourself — no need to wait on a rep.
              </p>
              <div className={styles.acceptRow}>
                <input
                  type="email" value={email} onChange={e => setEmail(e.target.value)}
                  placeholder="you@business.com"
                  className={styles.acceptInput}
                />
                <button
                  onClick={accept}
                  disabled={!email || accepting}
                  className={styles.acceptBtn}
                >
                  {accepting ? "Accepting…" : "Accept & Create Account →"}
                </button>
              </div>
              {error && <div className={styles.acceptError}>{error}</div>}
            </>
          ) : (
            // The ordinary case. There used to be a fourth branch below this
            // one — "your quote is being finalised", shown whenever no rep had
            // published yet — and it was a dead end on a link the merchant had
            // already been sent. It is gone: an unpublished quote is not a
            // wait any more, it is simply a quote nobody has pressed the
            // button on, and this is that button.
            <>
              <h2 className={styles.panelTitle}>Ready to move forward?</h2>
              <p className={styles.panelText}>
                Review the full quote, sign it, and enter your billing details — all on one
                secure page. That&apos;s everything; we&apos;ll set your account up from there.
              </p>
              <div className={styles.acceptRow}>
                <button
                  onClick={() => (checkoutUrl ? continueToBilling() : setConfirming(true))}
                  disabled={going}
                  className={styles.acceptBtn}
                >
                  {going ? "Opening…" : "Continue to Billing →"}
                </button>
              </div>
              {goError && <div className={styles.acceptError}>{goError}</div>}
            </>
          )}
        </div>

        <p className={styles.footnote}>
          Prefer to talk it through? Your AIO representative will follow up shortly too.
        </p>
      </div>
    </div>
  );
}
